export const collegeOptions = [
  "Vemana Institute of Technology",
  "RV College of Engineering",
  "BMS College of Engineering",
  "MS Ramaiah Institute of Technology",
  "PES University",
  "Dayananda Sagar College of Engineering",
  "New Horizon College of Engineering",
  "Nitte Meenakshi Institute of Technology",
  "BNM Institute of Technology",
  "CMR Institute of Technology",
  "SJCE Mysuru",
  "JSS Science and Technology University",
  "NIE Mysuru",
  "Reva University",
  "Presidency University",
  "KLE Technological University",
  "Siddaganga Institute of Technology",
  "BIT Bengaluru",
  "Acharya Institute of Technology",
  "Global Academy of Technology",
  "East West Institute of Technology",
  "RNS Institute of Technology",
  "Cambridge Institute of Technology",
  "Alliance University",
  "Jain University",
  "Christ University",
  "Manipal Institute of Technology",
  "NMAM Institute of Technology",
  "Mangalore Institute of Technology and Engineering",
  "Bangalore Institute of Technology"
];
